import type { CommandHandler } from '../cqrs/command-registry.js';
import type { QueryHandler } from '../cqrs/query-registry.js';
import {
  addAssetSubtaskHandler,
  assetDetailHandler,
  assetLibraryHandler,
  createAssetCategoryHandler,
  createAssetHandler,
  deleteAssetCategoryHandler,
  linkAssetFileHandler,
  linkAssetHandler,
  moveAssetCategoryHandler,
  moveAssetHandler,
  moveAssetReferenceHandler,
  promoteAssetReferenceHandler,
  removeAssetFileHandler,
  removeAssetReferenceHandler,
  removeAssetSubtaskHandler,
  tagAssetHandler,
  updateAssetCategoryHandler,
  unlinkAssetHandler,
  untagAssetHandler,
  updateAssetHandler,
  updateAssetSubtaskHandler,
} from './assets/index.js';
import { auditTrailHandler } from './audit/index.js';
import {
  addSubtaskHandler,
  archiveListHandler,
  boardViewHandler,
  taskListHandler,
  cardDetailHandler,
  commentHandler,
  createCardHandler,
  createListHandler,
  deleteCardHandler,
  linkCardHandler,
  putUnderLegendHandler,
  setLegendHandler,
  moveCardHandler,
  moveListHandler,
  syncIssuesHandler,
  removeSubtaskHandler,
  searchCardsHandler,
  unlinkCardHandler,
  updateCardHandler,
  updateListHandler,
  updateSubtaskHandler,
} from './board/index.js';
import {
  createMilestoneHandler,
  deleteMilestoneHandler,
  milestonePlanHandler,
  updateMilestoneHandler,
} from './milestones/index.js';
import {
  buildsHandler,
  deleteReleaseHandler,
  recordReleaseHandler,
  syncReleasesHandler,
  updateReleaseHandler,
} from './releases/index.js';

import {
  createPermissionGroupHandler,
  deletePermissionGroupHandler,
  permissionsHandler,
  renamePermissionGroupHandler,
  setPermissionRuleHandler,
  orderTeamPermissionGroupsHandler,
  setTeamPermissionGroupHandler,
  setUserPermissionGroupHandler,
} from './permissions/index.js';
import {
  createDesignDocHandler,
  deleteDesignDocHandler,
  designDocHandler,
  moveDesignDocHandler,
  renameDesignDocHandler,
  updateDesignDocHandler,
} from './docs/index.js';
import {
  agentsHandler,
  changePasswordHandler,
  completeSetupHandler,
  createAgentHandler,
  createUserHandler,
  issueAgentTokenHandler,
  meQueryHandler,
  peopleHandler,
  resetUserPasswordHandler,
  revokeAgentTokenHandler,
  updateAgentHandler,
  setUserRoleHandler,
  setUserStatusHandler,
  signInHandler,
  signOutHandler,
  updateProfileHandler,
} from './identity/index.js';
import {
  addProjectMemberHandler,
  addProjectTeamHandler,
  archiveProjectHandler,
  createProjectHandler,
  listProjectsHandler,
  projectBudgetHandler,
  projectCandidatesHandler,
  projectDashboardHandler,
  projectPeopleHandler,
  projectDetailHandler,
  projectTimelineHandler,
  projectWorkspaceHandler,
  removeProjectMemberHandler,
  removeProjectTeamHandler,
  restoreProjectHandler,
  updateProjectHandler,
} from './projects/index.js';
import { confirmUploadHandler, detachFileHandler, requestUploadHandler } from './files/index.js';
import {
  connectScmAppHandler,
  connectScmHandler,
  disconnectScmAppHandler,
  disconnectScmHandler,
  scmConnectionHandler,
} from './scm/index.js';
import {
  addTeamMemberHandler,
  createTeamHandler,
  deleteTeamHandler,
  removeTeamMemberHandler,
  teamListHandler,
  updateTeamHandler,
} from './teams/index.js';
import {
  deletedThingsHandler,
  purgeDeletedThingHandler,
  restoreDeletedThingHandler,
} from './recovery/index.js';
import { seeMentionHandler, waitingMentionsHandler } from './notifications/index.js';
import { logWorkHandler, removeWorkHandler } from './work/index.js';
import { healthQueryHandler } from './system/index.js';

/**
 * The complete API surface.
 *
 * A new feature registers its handler here and nowhere else. Keeping both lists
 * in one file means the whole surface of the server can be read at a glance,
 * and a handler that was written but never wired up is obvious.
 */
export const queryHandlers: readonly QueryHandler[] = [
  permissionsHandler,
  healthQueryHandler,
  meQueryHandler,
  peopleHandler,
  agentsHandler,
  teamListHandler,
  listProjectsHandler,
  projectBudgetHandler,
  projectDashboardHandler,
  projectCandidatesHandler,
  projectDetailHandler,
  projectPeopleHandler,
  projectTimelineHandler,
  projectWorkspaceHandler,
  boardViewHandler,
  taskListHandler,
  cardDetailHandler,
  searchCardsHandler,
  scmConnectionHandler,
  auditTrailHandler,
  deletedThingsHandler,
  assetLibraryHandler,
  assetDetailHandler,
  designDocHandler,
  milestonePlanHandler,
  buildsHandler,
  waitingMentionsHandler,
];

export const commandHandlers: readonly CommandHandler[] = [
  restoreDeletedThingHandler,
  purgeDeletedThingHandler,
  createPermissionGroupHandler,
  renamePermissionGroupHandler,
  deletePermissionGroupHandler,
  setPermissionRuleHandler,
  orderTeamPermissionGroupsHandler,
  setTeamPermissionGroupHandler,
  setUserPermissionGroupHandler,
  completeSetupHandler,
  signInHandler,
  signOutHandler,
  createAgentHandler,
  createUserHandler,
  issueAgentTokenHandler,
  revokeAgentTokenHandler,
  updateAgentHandler,
  setUserRoleHandler,
  setUserStatusHandler,
  resetUserPasswordHandler,
  changePasswordHandler,
  updateProfileHandler,
  createTeamHandler,
  updateTeamHandler,
  deleteTeamHandler,
  addTeamMemberHandler,
  removeTeamMemberHandler,
  createProjectHandler,
  updateProjectHandler,
  archiveProjectHandler,
  restoreProjectHandler,
  addProjectMemberHandler,
  removeProjectMemberHandler,
  addProjectTeamHandler,
  removeProjectTeamHandler,
  createCardHandler,
  updateCardHandler,
  deleteCardHandler,
  moveCardHandler,
  syncIssuesHandler,
  createListHandler,
  updateListHandler,
  moveListHandler,
  archiveListHandler,
  addSubtaskHandler,
  updateSubtaskHandler,
  removeSubtaskHandler,
  commentHandler,
  linkCardHandler,
  unlinkCardHandler,
  setLegendHandler,
  putUnderLegendHandler,
  requestUploadHandler,
  confirmUploadHandler,
  detachFileHandler,
  connectScmAppHandler,
  connectScmHandler,
  disconnectScmAppHandler,
  disconnectScmHandler,
  createAssetCategoryHandler,
  createAssetHandler,
  deleteAssetCategoryHandler,
  updateAssetCategoryHandler,
  updateAssetHandler,
  linkAssetFileHandler,
  linkAssetHandler,
  moveAssetReferenceHandler,
  promoteAssetReferenceHandler,
  removeAssetFileHandler,
  removeAssetReferenceHandler,
  moveAssetCategoryHandler,
  moveAssetHandler,
  tagAssetHandler,
  unlinkAssetHandler,
  untagAssetHandler,
  addAssetSubtaskHandler,
  updateAssetSubtaskHandler,
  removeAssetSubtaskHandler,
  createDesignDocHandler,
  renameDesignDocHandler,
  updateDesignDocHandler,
  moveDesignDocHandler,
  deleteDesignDocHandler,
  createMilestoneHandler,
  updateMilestoneHandler,
  deleteMilestoneHandler,
  recordReleaseHandler,
  updateReleaseHandler,
  deleteReleaseHandler,
  syncReleasesHandler,
  seeMentionHandler,
  logWorkHandler,
  removeWorkHandler,
];
