/**
 * sRGB and OKLab, both ways.
 *
 * Here because a ramp generated by mixing in sRGB is the mud this card was
 * warned about: `#eda363` toward `#242424` in sRGB goes grey through the middle,
 * because sRGB's channels are not perceptual and half way between two colours is
 * not half way between how they look. OKLab is built so that it is.
 *
 * The matrices are Björn Ottosson's, unchanged. They are the definition of the
 * space rather than a choice anybody here made, which is why they are written
 * out rather than derived.
 */

export interface Oklab {
  /** Perceptual lightness, 0 (black) to 1 (white). */
  readonly l: number;
  readonly a: number;
  readonly b: number;
}

export interface Rgb {
  readonly r: number;
  readonly g: number;
  readonly b: number;
}

/** `#rgb` or `#rrggbb`, in either case. Null for anything else. */
export function parseHex(hex: string): Rgb | null {
  const value = hex.trim().replace(/^#/u, '');

  if (!/^(?:[0-9a-f]{3}|[0-9a-f]{6})$/iu.test(value)) {
    return null;
  }

  // Doubled a character at a time rather than spread: spreading a string walks
  // code points, which is the wrong unit for something that is only ever hex
  // digits — and the rule against it is right that it mishandles the rest.
  const full = value.length === 3 ? value.replace(/./gu, (digit) => digit + digit) : value;

  return {
    r: Number.parseInt(full.slice(0, 2), 16) / 255,
    g: Number.parseInt(full.slice(2, 4), 16) / 255,
    b: Number.parseInt(full.slice(4, 6), 16) / 255,
  };
}

export function toHex({ r, g, b }: Rgb): string {
  return `#${[r, g, b].map(channelToHex).join('')}`;
}

function channelToHex(channel: number): string {
  const byte = Math.round(Math.min(1, Math.max(0, channel)) * 255);

  return byte.toString(16).padStart(2, '0');
}

/** Undo the sRGB transfer function, so the numbers are light rather than signal. */
function toLinear(channel: number): number {
  return channel <= 0.04045 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4;
}

function fromLinear(channel: number): number {
  return channel <= 0.0031308 ? channel * 12.92 : 1.055 * channel ** (1 / 2.4) - 0.055;
}

export function rgbToOklab(rgb: Rgb): Oklab {
  const red = toLinear(rgb.r);
  const green = toLinear(rgb.g);
  const blue = toLinear(rgb.b);

  const long = Math.cbrt(0.4122214708 * red + 0.5363325363 * green + 0.0514459929 * blue);
  const medium = Math.cbrt(0.2119034982 * red + 0.6806995451 * green + 0.1073969566 * blue);
  const short = Math.cbrt(0.0883024619 * red + 0.2817188376 * green + 0.6299787005 * blue);

  return {
    l: 0.2104542553 * long + 0.793617785 * medium - 0.0040720468 * short,
    a: 1.9779984951 * long - 2.428592205 * medium + 0.4505937099 * short,
    b: 0.0259040371 * long + 0.7827717662 * medium - 0.808675766 * short,
  };
}

export function oklabToRgb(lab: Oklab): Rgb {
  const long = (lab.l + 0.3963377774 * lab.a + 0.2158037573 * lab.b) ** 3;
  const medium = (lab.l - 0.1055613458 * lab.a - 0.0638541728 * lab.b) ** 3;
  const short = (lab.l - 0.0894841775 * lab.a - 1.291485548 * lab.b) ** 3;

  return {
    r: fromLinear(4.0767416621 * long - 3.3077115913 * medium + 0.2309699292 * short),
    g: fromLinear(-1.2684380046 * long + 2.6097574011 * medium - 0.3413193965 * short),
    b: fromLinear(-0.0041960863 * long - 0.7034186147 * medium + 1.707614701 * short),
  };
}

/** Somewhere between two colours, measured the way an eye measures it. */
export function mix(from: Oklab, to: Oklab, amount: number): Oklab {
  return {
    l: from.l + (to.l - from.l) * amount,
    a: from.a + (to.a - from.a) * amount,
    b: from.b + (to.b - from.b) * amount,
  };
}

/**
 * How light a colour looks, 0 to 1.
 *
 * OKLab's own `l`, which is what makes "is this a light theme" answerable from
 * a hex rather than asked of the person choosing it.
 */
export function lightnessOf(hex: string): number | null {
  const rgb = parseHex(hex);

  return rgb === null ? null : rgbToOklab(rgb).l;
}
