import { z } from 'zod';

import { defineCommand } from '../../envelope/command-definition.js';
import {
  repoFullNameSchema,
  scmEndpointSchema,
  scmProviderSchema,
  webhookSecretSchema,
} from '../scm-vocabulary.js';

/**
 * Points a project at the repository its work lands in.
 *
 * The secret is generated by the client and sent once. It could have been
 * generated here and returned, but a command returns identifiers — and a secret
 * that comes back in a response is a secret in a log, a proxy and a browser's
 * network panel. Generating it where it is shown means it crosses the wire once,
 * in the direction that has to happen anyway.
 *
 * Connecting again replaces what is there, which is how a secret is rotated: the
 * old one stops being accepted the moment the new one is stored.
 */
export const connectScmCommand = defineCommand(
  'scm.connect',
  z.object({
    projectId: z.string().uuid(),
    provider: scmProviderSchema,
    repoFullName: repoFullNameSchema,
    endpoint: scmEndpointSchema.nullish(),
    webhookSecret: webhookSecretSchema,
  }),
);

/**
 * Gives the connection credentials to ask the repository things, not only hear
 * from it.
 *
 * A webhook is one-way and only ever says what has just happened. Releases and
 * builds are a list the forge holds, and reading a list means asking for it — so
 * the Builds page needs a GitHub App, which signs for a short-lived token, where
 * commits and branches need nothing beyond the webhook.
 *
 * The private key is sent once and never returned. Replacing it is how it is
 * rotated, the same way the webhook secret works.
 */
export const connectScmAppCommand = defineCommand(
  'scm.connectApp',
  z.object({
    projectId: z.string().uuid(),
    appId: z
      .string()
      .trim()
      .regex(/^[0-9]+$/, 'An app id is the number GitHub shows on the app.'),
    installationId: z
      .string()
      .trim()
      .regex(/^[0-9]+$/, 'An installation id is the number in the installation URL.'),
    privateKey: z.string().trim().min(1, 'Paste the private key GitHub gave you.').max(20_000),
  }),
);

/** Takes the credentials away, leaving the webhook as it was. */
export const disconnectScmAppCommand = defineCommand(
  'scm.disconnectApp',
  z.object({ projectId: z.string().uuid() }),
);

/**
 * Forgets the repository.
 *
 * Deliveries that arrive afterwards are refused rather than kept, because there
 * is nothing left to verify them against.
 */
export const disconnectScmCommand = defineCommand(
  'scm.disconnect',
  z.object({ projectId: z.string().uuid() }),
);
