/// <reference types="vite/client" />

interface ImportMetaEnv {
  /** Baked-in server URL for the packaged self-host image. Optional. */
  readonly VITE_API_BASE_URL?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}

/** Generated by the `lpm-design-tokens` plugin in vite.config.ts. */
declare module 'virtual:lpm-tokens.css';
